### PR TITLE
Overall improvements

### PR DESCRIPTION
**Pull request by Hojosa**
Details are in the commits.

### CODE REVIEW

**Review by lesdmark — CHANGES_REQUESTED** [review]
The reason the materials look different, is because of them being crystalline materials not metallic. They should look the way they do. (for that matter, any blocks that are crystalline should look the same) Remove this and I can approve the request.

**Comment by Hojosa** [comment]
Done

**Comment by lesdmark** [comment]
I would have never thought to animate the Jukebox. Good job!

**Comment by Hojosa** [comment]
About that, thats actually from the legacy vanilla pack. Credits are in the json files for example, so i didnt thought to specify, that the other files are also from the vanilla pack. (except the material block ones, found those in my old jstr pack that, I made with the customizer back in the day)

**Pull request merged**
